language: ruby
rvm:
  - 2.7
  - 2.5
  - jruby-9.2.11.1
gemfile:
  - Gemfile
env:
  global:
    - JAVA_OPTS=-Djava.security.egd=file:/dev/urandom

addons:
  chrome: stable

cache:
  bundler: true

matrix:
  include:
    - gemfile: gemfiles/Gemfile.base
      rvm: 2.5
    - gemfile: gemfiles/Gemfile.edge
      rvm: 2.7
  allow_failures:
    - gemfile: gemfiles/Gemfile.edge
    - rvm: jruby-9.2.11.1

before_install:
  - gem update --system
  - chrome --version || true
  - google-chrome --version || true
  - chromium --version || true
  - chromium-browser --version || true

script: "bundle exec rake"
