name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.5', '2.7']
        gemfile: ['Gemfile']
        experimental: [false]
        include:
          - ruby: '2.5'
            gemfile: 'gemfiles/Gemfile.base'
            experimental: false
          - ruby: '2.7'
            gemfile: 'gemfiles/Gemfile.edge'
            experimental: true
          - ruby: 'jruby-9.2.11.1'
            gemfile: 'gemfiles/Gemfile.edge'
            experimental: true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.OS }}-ruby-${{ matrix.ruby }}-gems-${{ hashFiles(matrix.gemfile) }}-
          restore-keys: ${{ runner.OS }}-ruby-${{ matrix.ruby }}-
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
#      - name: Set up Bundler
#        run: gem update --system
      - name: Set up Dependencies
        run: |
          bundle config path vendor/bundle
          bundle config gemfile ${{ matrix.gemfile }}
          bundle install --jobs 4 --retry 3
      - name: Run specs
        run: bundle exec rake
